[phases.build]
cmds = ["pip install -r requirements.txt"]

[phases.setup]
nixPkgs = ["python311"]

[start]
cmd = "python manage.py migrate --noinput && gunicorn municipal.wsgi --bind 0.0.0.0:$PORT"

[variables]
DISABLE_COLLECTSTATIC = "1"