[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn municipal.wsgi --bind 0.0.0.0:$PORT"
healthcheckPath = "/admin/"
restartPolicyType = "ON_FAILURE"

[build.env]
PYTHON_VERSION = "3.11"

[deploy.env]
DEBUG = "False"
ALLOWED_HOSTS = "*"